name: Trading Signal Bot

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
    - cron: "0 0 * * *"  # Runs at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Trading Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: |
          python bot.py
